USE reviews;

INSERT INTO review_authur (name, picture_url) VALUES ("Estelle Mitchell", "https://s3.amazonaws.com/uifaces/faces/twitter/kerihenare/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kade Corkery", "https://s3.amazonaws.com/uifaces/faces/twitter/lebronjennan/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Devante Morissette IV", "https://s3.amazonaws.com/uifaces/faces/twitter/vanchesz/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Delmer Ullrich", "https://s3.amazonaws.com/uifaces/faces/twitter/nicolasfolliot/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Maria Walker", "https://s3.amazonaws.com/uifaces/faces/twitter/mocabyte/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mrs. Marcelo Leffler", "https://s3.amazonaws.com/uifaces/faces/twitter/matt3224/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kraig Bode", "https://s3.amazonaws.com/uifaces/faces/twitter/juamperro/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Louie Gutkowski", "https://s3.amazonaws.com/uifaces/faces/twitter/fronx/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Maia Macejkovic", "https://s3.amazonaws.com/uifaces/faces/twitter/gipsy_raf/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Petra Walter", "https://s3.amazonaws.com/uifaces/faces/twitter/normanbox/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kelly Lesch", "https://s3.amazonaws.com/uifaces/faces/twitter/billyroshan/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Leland Schinner", "https://s3.amazonaws.com/uifaces/faces/twitter/gmourier/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Weldon Abshire", "https://s3.amazonaws.com/uifaces/faces/twitter/geneseleznev/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Bruce Herman", "https://s3.amazonaws.com/uifaces/faces/twitter/noxdzine/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Tomas Kulas I", "https://s3.amazonaws.com/uifaces/faces/twitter/madewulf/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Leanna Cronin", "https://s3.amazonaws.com/uifaces/faces/twitter/bistrianiosip/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mr. Rosalia Zulauf", "https://s3.amazonaws.com/uifaces/faces/twitter/martip07/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jayden Volkman", "https://s3.amazonaws.com/uifaces/faces/twitter/michaelkoper/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Reymundo Lueilwitz PhD", "https://s3.amazonaws.com/uifaces/faces/twitter/joshmedeski/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Loraine Batz", "https://s3.amazonaws.com/uifaces/faces/twitter/elliotnolten/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Lia Yundt", "https://s3.amazonaws.com/uifaces/faces/twitter/jm_denis/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Darren Roob", "https://s3.amazonaws.com/uifaces/faces/twitter/aleinadsays/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kale Fadel", "https://s3.amazonaws.com/uifaces/faces/twitter/grahamkennery/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Lelah Gaylord", "https://s3.amazonaws.com/uifaces/faces/twitter/tgormtx/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Nikki Boyer", "https://s3.amazonaws.com/uifaces/faces/twitter/supjoey/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Aliya Hyatt", "https://s3.amazonaws.com/uifaces/faces/twitter/mylesb/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Judd Macejkovic", "https://s3.amazonaws.com/uifaces/faces/twitter/coreyginnivan/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Magnus Larkin", "https://s3.amazonaws.com/uifaces/faces/twitter/abovefunction/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mariano Turner", "https://s3.amazonaws.com/uifaces/faces/twitter/allagringaus/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Miss Myles Tremblay", "https://s3.amazonaws.com/uifaces/faces/twitter/allthingssmitty/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jewell Beier II", "https://s3.amazonaws.com/uifaces/faces/twitter/nilshelmersson/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Isai Lindgren", "https://s3.amazonaws.com/uifaces/faces/twitter/michaelbrooksjr/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Wava Hilll", "https://s3.amazonaws.com/uifaces/faces/twitter/silvanmuhlemann/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Emerson Lowe", "https://s3.amazonaws.com/uifaces/faces/twitter/prrstn/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Giovanni Douglas", "https://s3.amazonaws.com/uifaces/faces/twitter/foczzi/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Wilber Lind", "https://s3.amazonaws.com/uifaces/faces/twitter/alagoon/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Brad Von", "https://s3.amazonaws.com/uifaces/faces/twitter/ernestsemerda/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Ardith Botsford", "https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Miss Estell Koepp", "https://s3.amazonaws.com/uifaces/faces/twitter/terpimost/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Lori Becker", "https://s3.amazonaws.com/uifaces/faces/twitter/osmond/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Ralph Mertz", "https://s3.amazonaws.com/uifaces/faces/twitter/joemdesign/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Katlynn Stanton", "https://s3.amazonaws.com/uifaces/faces/twitter/kolage/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Tad Kub", "https://s3.amazonaws.com/uifaces/faces/twitter/sircalebgrove/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Evelyn Jacobson", "https://s3.amazonaws.com/uifaces/faces/twitter/badlittleduck/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jessica Keeling", "https://s3.amazonaws.com/uifaces/faces/twitter/ky/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Cornelius Murazik", "https://s3.amazonaws.com/uifaces/faces/twitter/jlsolerdeltoro/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Letitia Ebert", "https://s3.amazonaws.com/uifaces/faces/twitter/helderleal/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kelli Bosco MD", "https://s3.amazonaws.com/uifaces/faces/twitter/algunsanabria/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Malika Hackett", "https://s3.amazonaws.com/uifaces/faces/twitter/spedwig/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Adele Murphy Jr.", "https://s3.amazonaws.com/uifaces/faces/twitter/yigitpinarbasi/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Trace Dibbert", "https://s3.amazonaws.com/uifaces/faces/twitter/lhausermann/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mikayla Kutch", "https://s3.amazonaws.com/uifaces/faces/twitter/gearpixels/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Ms. Lourdes Anderson", "https://s3.amazonaws.com/uifaces/faces/twitter/catadeleon/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kendra Hammes", "https://s3.amazonaws.com/uifaces/faces/twitter/aaronalfred/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Susana Jacobi", "https://s3.amazonaws.com/uifaces/faces/twitter/falvarad/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mr. Priscilla Crist", "https://s3.amazonaws.com/uifaces/faces/twitter/andyisonline/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Connie Bartell", "https://s3.amazonaws.com/uifaces/faces/twitter/vinciarts/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Sophia Watsica", "https://s3.amazonaws.com/uifaces/faces/twitter/kijanmaharjan/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Rudolph Parisian", "https://s3.amazonaws.com/uifaces/faces/twitter/madebybrenton/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mr. Terry Rolfson", "https://s3.amazonaws.com/uifaces/faces/twitter/vaughanmoffitt/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jayda Fay", "https://s3.amazonaws.com/uifaces/faces/twitter/2fockus/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kimberly Gleason", "https://s3.amazonaws.com/uifaces/faces/twitter/_ragzor/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Eldred Wolff", "https://s3.amazonaws.com/uifaces/faces/twitter/magoo04/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Miss Kristin Leannon", "https://s3.amazonaws.com/uifaces/faces/twitter/sta1ex/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Thea Jacobson", "https://s3.amazonaws.com/uifaces/faces/twitter/michigangraham/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jessy Reynolds", "https://s3.amazonaws.com/uifaces/faces/twitter/geran7/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Issac Haley", "https://s3.amazonaws.com/uifaces/faces/twitter/horaciobella/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Casandra Hyatt IV", "https://s3.amazonaws.com/uifaces/faces/twitter/spbroma/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Delia Swift", "https://s3.amazonaws.com/uifaces/faces/twitter/xravil/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Sarina Jacobi Jr.", "https://s3.amazonaws.com/uifaces/faces/twitter/j04ntoh/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jan Altenwerth", "https://s3.amazonaws.com/uifaces/faces/twitter/marshallchen_/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Damon Kling Sr.", "https://s3.amazonaws.com/uifaces/faces/twitter/tereshenkov/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Maximilian Harvey", "https://s3.amazonaws.com/uifaces/faces/twitter/samgrover/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Santos O'Conner", "https://s3.amazonaws.com/uifaces/faces/twitter/mateaodviteza/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Dr. Jany Gorczany", "https://s3.amazonaws.com/uifaces/faces/twitter/thiagovernetti/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Manuel Dietrich II", "https://s3.amazonaws.com/uifaces/faces/twitter/ultragex/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Loraine Turner", "https://s3.amazonaws.com/uifaces/faces/twitter/paulfarino/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Marge Marks", "https://s3.amazonaws.com/uifaces/faces/twitter/sovesove/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Edmond Price", "https://s3.amazonaws.com/uifaces/faces/twitter/benoitboucart/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Randal Emard", "https://s3.amazonaws.com/uifaces/faces/twitter/stefvdham/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Miss Garrick Kohler", "https://s3.amazonaws.com/uifaces/faces/twitter/silvanmuhlemann/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Zola Leuschke PhD", "https://s3.amazonaws.com/uifaces/faces/twitter/davecraige/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Nikita Bode", "https://s3.amazonaws.com/uifaces/faces/twitter/aka_james/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Rickey Swift", "https://s3.amazonaws.com/uifaces/faces/twitter/SULiik/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Xavier Fisher", "https://s3.amazonaws.com/uifaces/faces/twitter/thaodang17/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Henriette Cummings", "https://s3.amazonaws.com/uifaces/faces/twitter/BroumiYoussef/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mariam Schmidt", "https://s3.amazonaws.com/uifaces/faces/twitter/samscouto/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Martin Brown", "https://s3.amazonaws.com/uifaces/faces/twitter/hugomano/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Terrance Breitenberg IV", "https://s3.amazonaws.com/uifaces/faces/twitter/andresdjasso/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Kimberly Ortiz DVM", "https://s3.amazonaws.com/uifaces/faces/twitter/cynthiasavard/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Victoria Hoppe", "https://s3.amazonaws.com/uifaces/faces/twitter/chadami/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mrs. Gabrielle Raynor", "https://s3.amazonaws.com/uifaces/faces/twitter/gkaam/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Domenick Turcotte V", "https://s3.amazonaws.com/uifaces/faces/twitter/stushona/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Daren Spinka", "https://s3.amazonaws.com/uifaces/faces/twitter/josemarques/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Eileen Dach", "https://s3.amazonaws.com/uifaces/faces/twitter/elliotlewis/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Jovanny Zemlak", "https://s3.amazonaws.com/uifaces/faces/twitter/adamawesomeface/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Amber Boehm", "https://s3.amazonaws.com/uifaces/faces/twitter/BenouarradeM/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Mrs. Beverly Dietrich", "https://s3.amazonaws.com/uifaces/faces/twitter/uxalex/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Zander Feeney", "https://s3.amazonaws.com/uifaces/faces/twitter/wearesavas/128.jpg");
INSERT INTO review_authur (name, picture_url) VALUES ("Brady Thiel", "https://s3.amazonaws.com/uifaces/faces/twitter/katiemdaly/128.jpg");


